"""create traffic analytics table

Revision ID: 87c42e53c0a9
Revises: 
Create Date: 2026-08-14 13:02:51.357402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c42e53c0a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('current_vehicle_count', sa.Integer(), nullable=False),
    sa.Column('total_vehicle_count', sa.Integer(), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('queue_length', sa.Integer(), nullable=False),
    sa.Column('waiting_vehicles', sa.Integer(), nullable=False),
    sa.Column('average_waiting_time', sa.Float(), nullable=False),
    sa.Column('maximum_waiting_time', sa.Float(), nullable=False),
    sa.Column('pcu', sa.Float(), nullable=False),
    sa.Column('traffic_flow', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_analytics')
    # ### end Alembic commands ###
